create sequence email_log_seq minvalue 1 start with 1 increment by 1;
create sequence item_seq minvalue 1 start with 1 increment by 1;
create sequence order_seq minvalue 1 start with 1 increment by 1;
create sequence order_stock_movement_seq minvalue 1 start with 1 increment by 1;
create sequence stock_movement_seq minvalue 1 start with 1 increment by 1;
create sequence user_seq minvalue 1 start with 1 increment by 1;
create table email_log (email_log_id int8 not null, body text not null, creation_date timestamp not null, log text, status varchar(255) not null, subject varchar(255) not null, to_email varchar(255) not null, primary key (email_log_id));
create table item (item_id int8 not null, disabled boolean not null, name varchar(255) not null, primary key (item_id));
create table order_stock_movement (order_stock_movement_id int8 not null, creation_date timestamp not null, order_id int8 not null, stock_movement_id int8 not null, primary key (order_stock_movement_id));
create table som_order (order_id int8 not null, creation_date timestamp not null, quantity int4 not null, status varchar(255) not null, item_id int8 not null, user_id int8 not null, primary key (order_id));
create table som_user (user_id int8 not null, disabled boolean not null, email varchar(255) not null, name varchar(255) not null, primary key (user_id));
create table stock_movement (stock_movement_id int8 not null, creation_date timestamp not null, operation varchar(255) not null, quantity int4 not null, item_id int8 not null, primary key (stock_movement_id));
alter table item add constraint uk_item_name unique (name);
alter table som_user add constraint uk_user_email unique (email);
alter table som_user add constraint uk_user_name unique (name);
alter table order_stock_movement add constraint fk_order_stock_movement_order_id foreign key (order_id) references som_order;
alter table order_stock_movement add constraint fk_order_stock_movement_stock_movement_id foreign key (stock_movement_id) references stock_movement;
alter table som_order add constraint fk_order_item_id foreign key (item_id) references item;
alter table som_order add constraint fk_order_user_id foreign key (user_id) references som_user;
alter table stock_movement add constraint fk_stock_movement_item_id foreign key (item_id) references item;
